### ISSUE TITLE
Incorrect Header Keywords for Keck getFilterName

### ISSUE THREAD

**Issue by jlibermann** [oliviermartin-lam/P3#6]
The header keywords in the `getFilterName` function (`/P3/telemetry/keckUtils.py`) should be changed to `hdr['FWINAME']`, `hdr['FWONAME']`, and `hdr["IFILTER"]`.

**Comment by oliviermartin-lam** [comment]
So actually the method to get the field from the hdr dictionary is not case sensitive, so it's not necessary to give the field names in capital letters.
